//基础数据
export const READ_DICT_GOODSCATEGORY = 'READ_DICT_GOODSCATEGORY';
export const READ_DICT_COMPTYPE = 'READ_DICT_COMPTYPE';
export const READ_DICT_ROUTERETURNTYPE = 'READ_DICT_ROUTERETURNTYPE';
export const READ_DICT_INSTORAGESTATE = 'READ_DICT_INSTORAGESTATE';
export const READ_DICT_OUTSTORAGESTATE = 'READ_DICT_OUTSTORAGESTATE';
export const READ_DICT_UNIT = 'READ_DICT_UNIT';
export const READ_DICT_CUSTTYPE = 'READ_DICT_CUSTTYPE';
export const READ_GOODS_SELECT = 'READ_GOODS_SELECT';
export const SAVE_LOG = 'SAVE_LOG';
//数据字典
export const READ_DICTIONARY_LIST = 'READ_DICTIONARY_LIST';
export const READ_DICTIONARY = 'READ_DICTIONARY';
export const SAVE_DICTIONARY = 'SAVE_DICTIONARY';
//导入配置
export const READ_IMPORTEXCELCONF_LIST = 'READ_IMPORTEXCELCONF_LIST';
export const READ_IMPORTEXCELCONF = 'READ_IMPORTEXCELCONF';
//角色
export const READ_ROLE_LIST = 'READ_ROLE_LIST';
export const READ_ROLE = 'READ_ROLE';
export const READ_ROLE_USER_SELECT = 'READ_ROLE_USER_SELECT';
export const READ_ROLE_MENU = 'READ_ROLE_MENU';
export const READ_ROLE_RIGHT = 'READ_ROLE_RIGHT';

//入库
export const READ_INSTORAGE_LIST = 'READ_INSTORAGE_LIST';
export const READ_INSTORAGE = 'READ_INSTORAGE';
export const SAVE_INSTORAGE = 'SAVE_INSTORAGE';
export const READ_INSTORAGE_FILE = 'READ_INSTORAGE_FILE';
export const READ_INSTORAGE_IMG = 'READ_INSTORAGE_IMG';
//出库
export const READ_OUTSTORAGE_LIST = 'READ_OUTSTORAGE_LIST';
export const READ_OUTSTORAGE = 'READ_OUTSTORAGE';
export const SAVE_OUTSTORAGE = 'SAVE_OUTSTORAGE';
export const READ_OUTSTORAGE_FILE = 'READ_OUTSTORAGE_FILE';
export const READ_OUTSTORAGE_IMG = 'READ_OUTSTORAGE_IMG';
export const READ_OUTSTORAGE_GOODS = 'READ_OUTSTORAGE_GOODS';
//平台路由
export const READ_ROUTERS = 'READ_ROUTERS';
export const READ_ROUTER = 'READ_ROUTER';
export const SAVE_ROUTER = 'SAVE_ROUTER';
export const REMOVEFILE = 'REMOVEFILE';

//仓库warehouses
export const READ_WAREHOUSES = 'READ_WAREHOUSES';
export const READ_WAREHOUSE = 'READ_WAREHOUSE';
export const SAVE_WAREHOUSE = 'SAVE_WAREHOUSE';

//供应商
export const READ_SUPPLIERS = 'READ_SUPPLIERS';
export const READ_SUPPLIER = 'READ_SUPPLIER';
export const SAVE_SUPPLIER = 'SAVE_SUPPLIER';
export const READ_SUPPLIER_FILE = 'READ_SUPPLIER_FILE';

//客户customer
export const READ_CUSTOMERS = 'READ_CUSTOMERS';
export const READ_CUSTOMER = 'READ_CUSTOMER';
export const SAVE_CUSTOMER = 'SAVE_CUSTOMER';
export const READ_CUSTOMER_FILE = 'READ_CUSTOMER_FILE';

//公司
export const READ_COMPANIES = 'READ_COMPANIES';
export const READ_COMPANY = 'READ_COMPANY';
export const SAVE_COMPANY = 'SAVE_COMPANY';
export const READ_COMPANY_FILE = 'READ_COMPANY_FILE';

//商品
export const READ_GOODSES = 'READ_GOODSES';
export const READ_GOODS = 'READ_GOODS';
export const READ_GOODS_FILE = 'READ_GOODS_FILE';
export const SAVE_GOODS = 'SAVE_GOODS';

//人员
export const READ_PERSONS = 'READ_PERSONS';
export const READ_PERSON = 'READ_PERSON';
export const READ_PERSONFILE = 'READ_PERSONFILE';
export const SAVE_PERSON = 'SAVE_PERSON';

//用户
export const USER_LOGIN = 'USER_LOGIN';
export const USER_CLEAR = 'USER_CLEAR';
export const USER_REG = 'USER_REG';
export const RESULT_CLEAR = 'RESULT_CLEAR';
export const READ_USER_MESSAGES = 'READ_USER_MESSAGES';
export const READ_USER_MESSAGE = 'READ_USER_MESSAGE';
export const MESSAGE_DONE = 'MESSAGE_DONE';
export const USER_LOGOUT = 'USER_LOGOUT';

//读主菜单信息
export const READ_MAIN_MENU = 'READ_MAIN_MENU'
//收藏
export const SET_FAVORITES = 'SET_FAVORITES'
export const READ_FAVORITES = 'READ_FAVORITES'
export const READ_FAVORITESLIST = 'READ_FAVORITESLIST'
export const READ_MENU_SELECT = 'READ_MENU_SELECT'

//图形
export const READ_CHART_DATA = 'READ_CHART_DATA'
