import '../common/lib';
import React from 'react';
import ReactDOM from 'react-dom';
import Head from '../component/Head';
import Left from '../component/Left';
import Bottom from '../component/Bottom';
import Content from '../component/Content';
ReactDOM.render(<Head   />, document.getElementById('react-head'));
ReactDOM.render(<Left   />, document.getElementById('react-left'));
ReactDOM.render(<Content   />, document.getElementById('react-content'));
ReactDOM.render(<Bottom   />, document.getElementById('react-bottom'));
